GET http://localhost:3100/config
frontauth:senhafrontend
###





POST http://localhost:3100/example
Content-Type: application/json

{
    "name":"Doug",
    "password":"cravado"
}

###

GET http://localhost:3100/config

###
POST  http://localhost:3100/users
Content-Type: application/json

{
    "name":"jjsd",
    "password":"cavalghoPjkesado",
    "email":"email@emfaikl.cum"
}

###
POST   http://localhost:3100/userslogin
Content-Type: application/json

{      
    "password":"yuri20323",
    "email":"email@email.com"
}

###

GET  http://localhost:3100/teste1
frontauth:senhafrontend
Content-Type: application/json
authsession:a93f71f8f69f731eb118dfd70ad849

{      
    "password":"yuri20323",
    "email":"email@email.com"
}

###

POST   http://localhost:3100/getusers
frontauth:senhafrontend
Content-Type: application/json

{      
    "password":"yuri20323",
    "email":"email@email.com"
}